// Mocks generated by Mockito 5.4.6 from annotations
// in star_consignment/test/views/barang/barang_konsinyasi_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i11;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:image_picker/image_picker.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:star_consignment/controllers/barang_controllers/katalog_controller.dart'
    as _i8;
import 'package:star_consignment/controllers/pengguna_controllers/klien_controller.dart'
    as _i6;
import 'package:star_consignment/models/barang_models/katalog_model.dart'
    as _i9;
import 'package:star_consignment/service/email_validator_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailValidatorService_1 extends _i1.SmartFake
    implements _i3.EmailValidatorService {
  _FakeEmailValidatorService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_2 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_3 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_4<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_5 extends _i1.SmartFake implements _i2.WriteBatch {
  _FakeWriteBatch_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_6 extends _i1.SmartFake
    implements _i2.LoadBundleTask {
  _FakeLoadBundleTask_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_7<T1 extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T1> {
  _FakeQuerySnapshot_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_8<T extends Object?> extends _i1.SmartFake
    implements _i2.Query<T> {
  _FakeQuery_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_9<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_10<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClientController].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientController extends _i1.Mock implements _i6.ClientController {
  MockClientController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  _i3.EmailValidatorService get emailValidator =>
      (super.noSuchMethod(
            Invocation.getter(#emailValidator),
            returnValue: _FakeEmailValidatorService_1(
              this,
              Invocation.getter(#emailValidator),
            ),
          )
          as _i3.EmailValidatorService);

  @override
  _i5.Stream<_i2.QuerySnapshot<Object?>> getClientsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getClientsStream, []),
            returnValue: _i5.Stream<_i2.QuerySnapshot<Object?>>.empty(),
          )
          as _i5.Stream<_i2.QuerySnapshot<Object?>>);

  @override
  _i5.Future<bool> checkEmailExists(String? email, {String? excludeId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkEmailExists,
              [email],
              {#excludeId: excludeId},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> createClient({
    required String? name,
    required String? phone,
    required String? email,
    required String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClient, [], {
              #name: name,
              #phone: phone,
              #email: email,
              #address: address,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> updateClient({
    required String? id,
    required String? name,
    required String? phone,
    required String? email,
    required String? address,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClient, [], {
              #id: id,
              #name: name,
              #phone: phone,
              #email: email,
              #address: address,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> deleteClient(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClient, [id]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> deductBorrowedItems({
    required String? clientId,
    required List<Map<String, dynamic>>? currentItems,
    required Map<int, int>? deductions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deductBorrowedItems, [], {
              #clientId: clientId,
              #currentItems: currentItems,
              #deductions: deductions,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> addBorrowedItemsDirect({
    required String? clientId,
    required List<Map<String, dynamic>>? newItems,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addBorrowedItemsDirect, [], {
              #clientId: clientId,
              #newItems: newItems,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [CatalogController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogController extends _i1.Mock implements _i8.CatalogController {
  MockCatalogController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  String get collectionName =>
      (super.noSuchMethod(
            Invocation.getter(#collectionName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#collectionName),
            ),
          )
          as String);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  set searchQuery(String? value) => super.noSuchMethod(
    Invocation.setter(#searchQuery, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedCategory(String? value) => super.noSuchMethod(
    Invocation.setter(#selectedCategory, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<_i2.QuerySnapshot<Object?>> getCatalogStream() =>
      (super.noSuchMethod(
            Invocation.method(#getCatalogStream, []),
            returnValue: _i5.Stream<_i2.QuerySnapshot<Object?>>.empty(),
          )
          as _i5.Stream<_i2.QuerySnapshot<Object?>>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void setCategory(String? category) => super.noSuchMethod(
    Invocation.method(#setCategory, [category]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i9.CatalogModel> filteredCatalog(List<_i9.CatalogModel>? items) =>
      (super.noSuchMethod(
            Invocation.method(#filteredCatalog, [items]),
            returnValue: <_i9.CatalogModel>[],
          )
          as List<_i9.CatalogModel>);

  @override
  List<String> uniqueCategories(List<_i9.CatalogModel>? items) =>
      (super.noSuchMethod(
            Invocation.method(#uniqueCategories, [items]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i5.Future<bool> checkNameExists(String? name, {String? excludeId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkNameExists,
              [name],
              {#excludeId: excludeId},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>> createItem({
    required String? name,
    required double? price,
    required String? category,
    _i10.XFile? imageFile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createItem, [], {
              #name: name,
              #price: price,
              #category: category,
              #imageFile: imageFile,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> updateItem({
    required String? id,
    required String? name,
    required double? price,
    required String? category,
    _i10.XFile? newImageFile,
    String? oldImagePath,
    bool? removeImage = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [], {
              #id: id,
              #name: name,
              #price: price,
              #category: category,
              #newImageFile: newImageFile,
              #oldImagePath: oldImagePath,
              #removeImage: removeImage,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> deleteItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [id]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i2.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_2(this, Invocation.getter(#app)),
          )
          as _i4.FirebaseApp);

  @override
  String get databaseId =>
      (super.noSuchMethod(
            Invocation.getter(#databaseId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
          )
          as String);

  @override
  _i2.Settings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettings_3(this, Invocation.getter(#settings)),
          )
          as _i2.Settings);

  @override
  set app(_i4.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? value) => super.noSuchMethod(
    Invocation.setter(#databaseId, value),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i2.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionPath]),
            returnValue: _FakeCollectionReference_4<Map<String, dynamic>>(
              this,
              Invocation.method(#collection, [collectionPath]),
            ),
          )
          as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_5(this, Invocation.method(#batch, [])),
          )
          as _i2.WriteBatch);

  @override
  _i5.Future<void> clearPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPersistence, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.LoadBundleTask loadBundle(_i11.Uint8List? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundle, [bundle]),
            returnValue: _FakeLoadBundleTask_6(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
          )
          as _i2.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i2.GetOptions? options = const _i2.GetOptions(),
    required _i2.FromFirestore<T>? fromFirestore,
    required _i2.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedQueryWithConverterGet,
              [name],
              {
                #options: options,
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              },
            ),
            returnValue: _i5.Future<_i2.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_7<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.QuerySnapshot<T>>);

  @override
  _i5.Future<_i2.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i2.GetOptions? options = const _i2.GetOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#namedQueryGet, [name], {#options: options}),
            returnValue:
                _i5.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_7<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i2.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#collectionGroup, [collectionPath]),
            returnValue: _FakeQuery_8<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
          )
          as _i2.Query<Map<String, dynamic>>);

  @override
  _i5.Future<void> disableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#disableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [documentPath]),
            returnValue: _FakeDocumentReference_9<Map<String, dynamic>>(
              this,
              Invocation.method(#doc, [documentPath]),
            ),
          )
          as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i5.Future<void> enableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#enableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotsInSync, []),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);

  @override
  _i5.Future<T> runTransaction<T>(
    _i2.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_10<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingWrites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setIndexConfigurationFromJSON, [json]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
